# Application Configuration

# Document Processing Configuration
document:
  default_path: "./job_descriptions"
  chunk_size: 1000
  chunk_overlap: 200
  embedding_model: "all-MiniLM-L6-v2"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "app_performance.log"
    - type: "console"

# Add other configuration sections here as needed
# For example:
# api:
#   base_url: "https://api.example.com"
#   timeout: 30
#
# database:
#   host: "localhost"
#   port: 5432
#   name: "myapp" 