# Application Configuration
app:
  title: "Job Description ChatBot"
  logo_path: "assets/jd_chat_bot.png"
  css_path: "assets/styles.css"
  instructions:
    - "Click on 'Document Embeddings' to prepare the data."
    - "Ask questions related to your documents."
  about: "This app uses Llama3 8B model to answer questions based on your Job Description documents."
  ui:
    sidebar_width: 200
    main_header: "Chat with your Job Description documents using Llama3 8B"
    input_label: "Enter your question from Documents!!"
    button_text: "Document Embeddings"

# Document Processing Configuration
document:
  default_path: "./job_descriptions"
  chunk_size: 1000
  chunk_overlap: 200
  embedding_model: "all-MiniLM-L6-v2"

# RAG Model Configuration
rag_model:
  model_name: "Llama3-8b-8192"
  temperature: 0.7
  max_tokens: 8192
  prompt_template: |
    Answer the questions based on the provided context only.
    Please provide the most accurate response based on the question.
    <context>
    {context}
    </context>
    Question: {input}

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "app_performance.log"
    - type: "console"

